# Generated by Django 5.1.7 on 2025-03-16 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('municipal_id', models.AutoField(primary_key=True, serialize=False)),
                ('municipal_name', models.CharField(max_length=255)),
                ('municipal_rate', models.DecimalField(decimal_places=8, max_digits=9)),
                ('education_rate', models.DecimalField(decimal_places=8, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('assessment_roll_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assessment_value', models.IntegerField()),
                ('municipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_assessment.municipality')),
            ],
        ),
    ]
