# Generated by Django 5.1.7 on 2025-03-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='assessment_roll_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
